# Generated by Django 3.1.4 on 2020-12-25 17:22

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


def load_data(apps, schema_editor):
    DATA_FILENAME = 'topo/data/fr___ebloc_targassonne.geojson'

    Topo = apps.get_model('topo', 'Topo')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['features']:
            try:
                obj_type = obj['geometry']['type']
                if obj_type == 'Point':
                    coordinates = obj['geometry']['coordinates']
                    name = obj['name']
                    longitude = coordinates[0]
                    latitude = coordinates[1]
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Topo(name=name, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
