# Generated by Django 3.1.4 on 2020-12-25 20:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0003_auto_20201225_1741'),
    ]

    operations = [

    ]
