# Generated by Django 3.1.4 on 2020-12-25 20:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0004_topo_geom'),
    ]

    operations = [
    ]
