# Generated by Django 3.1.4 on 2020-12-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0005_auto_20201225_2019'),
    ]

    operations = [

    ]
