# Generated by Django 3.1.4 on 2020-12-26 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0007_auto_20201226_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='calque',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'FACILE'), (2, 'DIFFICILE'), (3, 'ASSEZ_DIFFICILE'), (4, 'TRES_DIFFICILE'), (5, 'EXTREMEMENT_DIFFICILE')], default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='code_topo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='line',
            name='compression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='cota',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='line',
            name='da',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='da_cota',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='line',
            name='descente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='elim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='expo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='line',
            name='hauteur',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='inclin',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='line',
            name='incontournable',
            field=models.IntegerField(choices=[(0, 'Aucun'), (1, 'Secteur'), (2, 'Site')], default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='jette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='line_nb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='morfo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='orientation',
            field=models.CharField(blank=True, choices=[('n', 'Nord'), ('s', 'Sud'), ('e', 'Est'), ('o', 'Ouest'), ('ne', 'Nord-Est'), ('se', 'Sud_Est'), ('no', 'Nord-Ouest'), ('so', 'Sud-Ouest')], max_length=2),
        ),
        migrations.AddField(
            model_name='line',
            name='physique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='plans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='reglette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='reta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='technique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='touche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='trav',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='orientation',
            field=models.CharField(choices=[('n', 'Nord'), ('s', 'Sud'), ('e', 'Est'), ('o', 'Ouest'), ('ne', 'Nord-Est'), ('se', 'Sud_Est'), ('no', 'Nord-Ouest'), ('so', 'Sud-Ouest')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='line',
            name='photo',
            field=models.ImageField(null=True, upload_to='lines/.'),
        ),
    ]
