# Generated by Django 3.1.4 on 2020-12-26 18:35

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from django.contrib.gis.geos import Polygon




def load_data(apps, schema_editor):

    Sector = apps.get_model('topo', 'Sector')
    DATA_FILENAME = 'topo/data/sectors.geojson'

    jsonfile = DATA_FILENAME
    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['features']:
            try:
                obj_type = obj['geometry']['type']
                if obj_type == 'Polygon':
                    name = obj['properties']['name']
                    color = obj['properties']['_umap_options']['color']

                    coordinates = Polygon(obj['geometry']['coordinates'][0])
                    Sector(name=name, color=color, coordinates=coordinates).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0008_auto_20201226_1829'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
