# Generated by Django 3.1.4 on 2021-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0013_auto_20210105_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='type',
            field=models.IntegerField(choices=[(1, 'Parking'), (2, 'Camping')], default=1),
            preserve_default=False,
        ),
    ]
