# Generated by Django 3.1.4 on 2021-01-05 10:36

from django.db import migrations
import json
from pathlib import Path
from django.contrib.gis.geos import fromstr


class Migration(migrations.Migration):

    def load_data(apps, _):
        DATA_FILENAME = 'topo/data/infos.geojson'

        Other = apps.get_model('topo', 'Other')
        jsonfile = Path(__file__).parents[2] / DATA_FILENAME

        with open(str(jsonfile)) as datafile:
            objects = json.load(datafile)
            for obj in objects['features']:
                try:
                    name = obj['properties']['name']
                    coordinates = obj['geometry']['coordinates']
                    type = 1 if 'Parking' in name else 2
                    longitude = coordinates[0]
                    latitude = coordinates[1]
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Other(name=name, geom=location, type=type).save()
                except KeyError:
                    pass


    dependencies = [
        ('topo', '0014_other_type'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
