# Generated by Django 3.1.4 on 2021-01-07 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0015_auto_20210105_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='coordinates',
            new_name='geom',
        ),
        migrations.AddField(
            model_name='line',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
