# Generated by Django 3.1.4 on 2021-01-08 08:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0016_auto_20210107_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.IntegerField(choices=[(0, 'Bloc'), (1, 'Ligne'), (2, 'Les deux')], default=0)),
                ('photo', models.ImageField(upload_to='photo/.')),
                ('orientation', models.CharField(choices=[('n', 'Nord'), ('s', 'Sud'), ('e', 'Est'), ('o', 'Ouest'), ('ne', 'Nord-Est'), ('se', 'Sud_Est'), ('no', 'Nord-Ouest'), ('so', 'Sud-Ouest')], max_length=2)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='bloc',
        ),
        migrations.DeleteModel(
            name='Topo',
        ),
        migrations.RemoveField(
            model_name='line',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='line',
            name='point',
        ),
        migrations.AddField(
            model_name='bloc',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='line',
            name='bloc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topo.bloc'),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.AddField(
            model_name='photo',
            name='target_bloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topo.bloc'),
        ),
        migrations.AddField(
            model_name='photo',
            name='target_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topo.line'),
        ),
    ]
