# Generated by Django 3.1.4 on 2021-01-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0018_auto_20210108_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='target_bloc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topo.bloc'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='target_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topo.line'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='target_type',
            field=models.IntegerField(choices=[(0, 'Bloc'), (1, 'Ligne'), (2, 'Artistique')], default=0),
        ),
    ]
