# Generated by Django 3.1.4 on 2021-01-21 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0019_auto_20210115_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incontournable', models.IntegerField(choices=[(0, 'Aucun'), (1, 'Secteur'), (2, 'Site')], default=0)),
                ('code_topo', models.CharField(blank=True, max_length=10)),
                ('da', models.BooleanField(default=False)),
                ('da_cota', models.CharField(blank=True, max_length=10)),
                ('hauteur', models.FloatField(default=0)),
                ('inclin', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('orientation', models.CharField(blank=True, choices=[('n', 'Nord'), ('s', 'Sud'), ('e', 'Est'), ('o', 'Ouest'), ('ne', 'Nord-Est'), ('se', 'Sud_Est'), ('no', 'Nord-Ouest'), ('so', 'Sud-Ouest')], max_length=2)),
                ('expo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('trav', models.CharField(blank=True, max_length=3)),
                ('descente', models.BooleanField(default=False)),
                ('morfo', models.BooleanField(default=False)),
                ('reglette', models.BooleanField(default=False)),
                ('plans', models.BooleanField(default=False)),
                ('reta', models.BooleanField(default=False)),
                ('compression', models.BooleanField(default=False)),
                ('jette', models.BooleanField(default=False)),
                ('technique', models.BooleanField(default=False)),
                ('physique', models.BooleanField(default=False)),
                ('touche', models.BooleanField(default=False)),
                ('elim', models.BooleanField(default=False)),
                ('top', models.BooleanField(default=False)),
                ('obs_fr', models.CharField(blank=True, max_length=1000)),
                ('obs_es', models.CharField(blank=True, max_length=1000)),
                ('obs_en', models.CharField(blank=True, max_length=1000)),
                ('obs_cat', models.CharField(blank=True, max_length=1000)),
                ('da_nom', models.CharField(blank=True, max_length=50)),
                ('ext', models.CharField(blank=True, max_length=5)),
                ('var', models.CharField(blank=True, max_length=5)),
                ('avis_1', models.CharField(blank=True, max_length=5)),
                ('avis_2', models.CharField(blank=True, max_length=5)),
                ('annee', models.CharField(blank=True, max_length=5)),
                ('ouvert', models.CharField(blank=True, max_length=50)),
                ('first_ascent', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='line',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='line',
            name='avis_1',
        ),
        migrations.RemoveField(
            model_name='line',
            name='avis_2',
        ),
        migrations.RemoveField(
            model_name='line',
            name='code_topo',
        ),
        migrations.RemoveField(
            model_name='line',
            name='compression',
        ),
        migrations.RemoveField(
            model_name='line',
            name='da',
        ),
        migrations.RemoveField(
            model_name='line',
            name='da_cota',
        ),
        migrations.RemoveField(
            model_name='line',
            name='da_nom',
        ),
        migrations.RemoveField(
            model_name='line',
            name='descente',
        ),
        migrations.RemoveField(
            model_name='line',
            name='elim',
        ),
        migrations.RemoveField(
            model_name='line',
            name='expo',
        ),
        migrations.RemoveField(
            model_name='line',
            name='ext',
        ),
        migrations.RemoveField(
            model_name='line',
            name='first_ascent',
        ),
        migrations.RemoveField(
            model_name='line',
            name='hauteur',
        ),
        migrations.RemoveField(
            model_name='line',
            name='inclin',
        ),
        migrations.RemoveField(
            model_name='line',
            name='incontournable',
        ),
        migrations.RemoveField(
            model_name='line',
            name='jette',
        ),
        migrations.RemoveField(
            model_name='line',
            name='morfo',
        ),
        migrations.RemoveField(
            model_name='line',
            name='obs_cat',
        ),
        migrations.RemoveField(
            model_name='line',
            name='obs_en',
        ),
        migrations.RemoveField(
            model_name='line',
            name='obs_es',
        ),
        migrations.RemoveField(
            model_name='line',
            name='obs_fr',
        ),
        migrations.RemoveField(
            model_name='line',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='line',
            name='ouvert',
        ),
        migrations.RemoveField(
            model_name='line',
            name='physique',
        ),
        migrations.RemoveField(
            model_name='line',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='line',
            name='reglette',
        ),
        migrations.RemoveField(
            model_name='line',
            name='reta',
        ),
        migrations.RemoveField(
            model_name='line',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='line',
            name='top',
        ),
        migrations.RemoveField(
            model_name='line',
            name='touche',
        ),
        migrations.RemoveField(
            model_name='line',
            name='trav',
        ),
        migrations.RemoveField(
            model_name='line',
            name='var',
        ),
        migrations.AddField(
            model_name='line',
            name='line_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topo.lineinfo'),
        ),
    ]
