# Generated by Django 3.1.4 on 2021-01-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0020_auto_20210121_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='note',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='number',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='orientation',
        ),
    ]
