# Generated by Django 3.1.4 on 2021-01-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0021_auto_20210127_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='target_bloc',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='target_line',
        ),
        migrations.AddField(
            model_name='line',
            name='photos',
            field=models.ManyToManyField(to='topo.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='target_type',
            field=models.IntegerField(choices=[(0, 'Bloc'), (1, 'Ligne'), (2, 'Artistique')], default=1),
        ),
    ]
