# Generated by Django 3.1.4 on 2021-01-28 09:11

from django.db import migrations
import os


class Migration(migrations.Migration):

    def load_data(self):
        dir_path = 'ebloc/topo/static/img/photo/line'
        photos = os.listdir(dir_path)
        Photo = apps.get_model('topo', 'Photo')

        for p in photos:
            Photo(p)

    dependencies = [
        ('topo', '0022_auto_20210128_0909'),
    ]

    operations = [
    ]
