# Generated by Django 3.1.4 on 2021-01-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0023_auto_20210128_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
